version: '3.7'
services:
  server:
    container_name: ftp-server1
    build:
      context: ./
      dockerfile: FtpServerDockerfile
      args:
        - FTP_USER=username
        - FTP_PASS=password
    ports:
      - '3000-3001:20-21'
      - '21200-21210:21100-21110'
    volumes:
      - logs:/var/log/
      - file:/home/vsftpd/username/
  sidecar:
    container_name: sidecar-s1
    build:
      context: ./
      dockerfile: sideCarDockerfile
    volumes:
      - logs:/var/log/
      - file:/home/
    ports:
      - '3022:22'
  logviewer:
    container_name: logviewer1
    build:
      context: ./
      dockerfile: logViewerDockerfile
    environment:
      - LOG_DIR=./log/
      - ID=server1
      - SERVER_IP=192.168.1.188
      - SERVER_PORT=3001
      - SSH_PORT=3022
      - DB_NAME=db0
      - DB_IP=192.168.1.188
      - DB_PORT=8089
      - POSTGRES_IP=192.168.1.188
      - POSTGRES_PORT=54320
      - POSTGRES_USER=admin
      - POSTGRES_DB_NAME=servers
      - POSTGRES_PASSWORD=admin
      - PYTHONUNBUFFERED=1
    volumes:
      - logs:/logviewer/log
volumes:
  logs:
  file:
